tap "homebrew/bundle"
# tap "homebrew/cask" == It seems it is no longer neccesary
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
# tap "homebrew/core" == It seems it is no longer neccesary
tap "homebrew/services"
tap "buo/cask-upgrade"
tap "hashicorp/tap"
tap "beeftornado/rmtree"

brew "awscli"
brew "curl"
brew "cdktf"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "hashicorp/tap/terraform"
brew "htop"
brew "ijq"
brew "jq"
brew "just"
brew "mas"
brew "maven"
brew "node"
brew "nvm"
brew "openjdk@11"
brew "poetry"
brew "pre-commit"
brew "python@3.12"
brew "telnet"
brew "vim"
brew "watch"
brew "wget"

cask 'dropbox'
cask 'evernote'
cask "font-jetbrains-mono"
cask "font-commit-mono"
cask "font-fira-code"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "synology-drive"
cask "visual-studio-code"

mas "The Unarchiver", id: 425424353
mas "Microsoft 365", id: 1450038993
#mas "TechSmith Snagit 2024", id: 6451154048